### ISSUE TITLE
请教源代码行数

### ISSUE THREAD

**Issue by nobodxbodon** [ixlang/XStudio#1]
你好，有幸看到 [此答](https://www.zhihu.com/question/477832428/answer/3528662319) ，其中提到 IDE 代码量约七万。
但用 scc 看 .x 17865行，.xcs 1864行，不知漏了哪些？

**Comment by ixlang** [comment]
> 你好，有幸看到 [此答](https://www.zhihu.com/question/477832428/answer/3528662319) ，其中提到 IDE 代码量约七万。 但用 scc 看 .x 17865行，.xcs 1864行，不知漏了哪些？

你好，仓库的版本比较久远，是三年多以前1.x版本的代码，答文中说的源代码行数为目前2.x版本，其中包含ide主框架 、 xlang开发插件、代码格式化插件 、 C++开发插件 、android 开发插件和java开发插件，不含库，国内git访问不稳定，梯子麻烦，所以git很久未更新，谢谢。
